# Generated by Django 4.2.4 on 2023-09-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
            },
        ),
    ]
