# Generated by Django 4.2.4 on 2023-09-18 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing_management_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='last_time',
            field=models.DateTimeField(verbose_name='Время рассылки'),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец получателей')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='mailing_management_service.recipient', verbose_name='Получатели'),
        ),
    ]
