# Generated by Django 4.2.4 on 2023-09-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management_service', '0002_alter_mailinglog_last_time_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('deactivate_mailing', 'Can deactivate mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
